registerRoute("playground", "playground.luac")
registerRoute("todo", "todo.luac")
registerRoute("okhttp-contributors", "okhttp-contributors.luac")
loadFeature("reading-list")
setStartRoute("playground")
