registerRoute("playground", "playground.luac")
registerRoute("todo", "todo.luac")
registerRoute("okhttp-contributors", "okhttp-contributors.luac")
registerRoute("reading-list", "reading-list.luac")
setStartRoute("playground")
